######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 29 13:36:48 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . gui old
INCLUDEPATH += . gui old

# Input
HEADERS += new_membrane_test.h \
           gui/membrane_test_gui.h \
           old/membrane_test.h \
           old/membrane_test_ui.h
SOURCES += new_membrane_test.cpp \
           gui/main.cpp \
           gui/membrane_test_gui.cpp \
           old/membrane_test.cpp \
           old/membrane_test_ui.cpp
