######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 24 18:16:03 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += membrane_test_gui.h
SOURCES += main.cpp membrane_test_gui.cpp
