######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 21 15:41:35 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += membrane_test_gui.h
SOURCES += main.cpp membrane_test_gui.cpp
