######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 29 19:06:58 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += membrane_test_gui.h
SOURCES += main.cpp membrane_test_gui.cpp
