######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 26 15:07:06 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += membrane_test_gui.h
SOURCES += main.cpp membrane_test_gui.cpp
